apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: ecommerce
data:
  EUREKA_SERVER: "http://eureka-server:8761/eureka"
  CONFIG_SERVER: "http://config-server:8888"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  ZIPKIN_BASE_URL: "http://zipkin:9411"
  SPRING_PROFILES_ACTIVE: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resilience-config
  namespace: ecommerce
data:
  CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD: "50"
  CIRCUIT_BREAKER_WAIT_DURATION_MS: "5000"
  RETRY_MAX_ATTEMPTS: "3"
